# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbTibc5EntOdTigmWZg255i6bbIkr7-7
"""


import nltk
nltk.download('punkt')
nltk.download('average_perceptron_tagger')
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

"""**pretraitement des données**

charger le fichier
"""

with open('les-crimes-de-l_amour.txt','r',encoding='utf-8') as f :

    text = f.read().replace('\n','')

"""pretraiter"""

def preprocess(data):
  text = text.lower() # convertir en miniscules
  tokens = word_tokenize(text) #tokenisation du texte
  stop_words = set(stopwords.words('english'))#remplacer english par french
  tokens = [token for token in tokens if token not in stop_words and token not in string.punctuation] #suppression des mots vides
  lemmatizer = WordNetLemmatizer()
  tokens = [lemmatizer.lemmatize(token) for token in tokens] #lemmatisation
  return tokens

  corpus =[preprocess(text) for token in tokens]

"""Definir la fonction de similarite"""

def get_most_relevant_sentence(query) :
  # Prétraitement de la requête
  query = preprocess(query)

  max_similarite = 0
  get_most_relevant_sentence = "";

  for text in corpus:
    similarite = len(set(query).intersection(text)) / float(len(set(query).union(text)))
    if similarite > max_similarite:
      max_similarite = similarite

      get_most_relevant_sentence = " ".join(text)
  return get_most_relevant_sentence

"""Definir le chatbot"""

def chatbot(user_query,text):
      if user_query.strip():
        return "Je n'ai pas compris votre question. Pouvez-vous reformuler?"

        # Trouver la phrase la plus pertinente
      relevant_sentence == get_most_relevant_sentence(user_query,text)

      if relevant_sentence and relevant_sentence.strip() :

       return " Voici ce que j'ai trouve:\n {relevant_sentence}"
      else :
       return "Je n'ai pas trouvé de réponse à votre question. Pouvez-vous reformuler?"

"""Creation d'une application Streamlit"""

import streamlit as st

def main() :

    st.title ("Chatbot de l'amour")

    st.write ("Bonjour ! Je suis un chatbot. Demandez-moi n'importe quoi sur l'amour.")

    user_query = st.text_input("Comment puis-je vous aider")

    if user_query.strip():

      response = chatbot(user_query,text)
      st.write("Reponnse : " , + response)

if __name__ == "__main__" :

    main()